### ISSUE TITLE
Rust embedded standard library (no_std) target is not supported

### ISSUE THREAD

**Issue by blue-freedom-technologies** [rust-random/getrandom#375]
Hello,

If we have in our cargo.toml like is describe in [here](https://docs.rs/getrandom/latest/getrandom/#rdrand-on-x86).

[target.'cfg(all(any(target_arch = "wasm32", target_arch = "wasm64"), target_os = "unknown"))'.dependencies]
getrandom = { version = "0.2.10", features = ["rdrand"] }

Why we are getting this error ? Is the fallback failing ?

![image](https://github.com/rust-random/getrandom/assets/142290531/e32a9293-a5b3-4466-87ae-e5eff13b843a)

Are we doing something wrong ?

Cheers,

**Comment by newpavlov** [comment]
As explicitly written in the [docs](https://docs.rs/getrandom/latest/getrandom/#rdrand-on-x86), `rdrand` has effect only on x86 and x86-64 targets.

For WASM targets you either have to use the `js` feature (and thus depend on `wasm-bindgen`), or introduce your own [custom backend](https://docs.rs/getrandom/latest/getrandom/macro.register_custom_getrandom.html).

**Comment by blue-freedom-technologies** [comment]
Hi @newpavlov ,

Thank you for your answer.

Since we are working with [esp-hal](https://github.com/esp-rs/esp-hal). In theory we should have a configuration like this, right ?

[target.'cfg(all(any( target_arch = "x86_64"), target_os = "unknown"))'.dependencies]
getrandom = { version = "0.2.10", features = ["rdrand"] }

Cheers,

**Comment by newpavlov** [comment]
ESP32 systems do not use x86 CPUs and WASM even less relevant. If you are just starting with embedded programming, it may be easier for you to start with [ESP IDF](https://github.com/esp-rs/esp-idf-hal), `getrandom` supports `*-epdif` targets out of box.

**Comment by blue-freedom-technologies** [comment]
If we use the [esp-idf-hal](https://github.com/esp-rs/esp-idf-hal)

getrandom = { version = "0.2.10"}

We will get this.
![image](https://github.com/rust-random/getrandom/assets/142290531/5a3f26b1-a442-42a1-b1ea-5887389736ad)

Now coming back to the [esp-hal](https://github.com/esp-rs/esp-hal).

For my understanding so far for the no_std environments makes not point using the getrandom library since we have no advantage using it, right?

Cheers,

**Comment by newpavlov** [comment]
What target are you compiling your project for? As I wrote in my previous comment, the ESP IDF backend will work only for `*-espidf` targets.

Since it looks like you are only starting with ESP, I strongly suggest asking help in the esp-rs Matrix server.

>For my understanding so far for the no_std environments makes no point using the getrandom library since we have no advantage using it, right?

Depends on whether a dependency in your project uses `getrandom` or not. If you don't have such dependencies, then you can skip it.

**Comment by blue-freedom-technologies** [comment]
We have a dependency [subxt](https://github.com/paritytech/subxt/blob/master/Cargo.toml#L55) that uses getrandom = { version = "0.2", default-features = false }.

Our target is  "riscv32imac-esp-espidf".

`"I strongly suggest asking help in the esp-rs Matrix server.". `

Unfortunately we already did that. 

Cheers,

**Comment by newpavlov** [comment]
>Our target is "riscv32imac-esp-espidf".

Weird. As you can see [here](https://github.com/rust-random/getrandom/blob/master/src/lib.rs#L257-L258) compiling for this target should enable backend which uses [`esp_fill_random`](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/random.html#_CPPv415esp_fill_randomPv6size_t).

Double check that your code is indeed compiled for this target. You also could try the following code:
```rust
#[cfg(target_os = "espidf")]
compile_error!("Target OS is ESP IDF");
#[cfg(not(target_os = "espidf"))]
compile_error!("Target OS is not ESP IDF");
```

**Comment by blue-freedom-technologies** [comment]
Yep. We even did this bellow for the [esp-idf-hal](https://github.com/esp-rs/esp-idf-hal):

```
use core::{ffi::c_void};
use getrandom::Error;

extern "C" {
    fn esp_fill_random(buf: *mut c_void, len: usize) -> u32;
}

pub fn getrandom_inner(dest: &mut [u8]) -> Result<(), Error> {
    // Not that NOT enabling WiFi, BT, or the voltage noise entropy source (via `bootloader_random_enable`)
    // will cause ESP-IDF to return pseudo-random numbers based on the voltage noise entropy, after the initial boot process:
    // https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/random.html
    //
    // However tracking if some of these entropy sources is enabled is way too difficult to implement here
    unsafe { esp_fill_random(dest.as_mut_ptr().cast(), dest.len()) };

    Ok(())
}


use prototype_app::getrandom_inner;
use getrandom::register_custom_getrandom;

register_custom_getrandom!(getrandom_inner);


getrandom = { version = "0.2", features = ["custom"] }
subxt = { version = "0.31.0", default-features = false, features = ["unstable-metadata", "native", "jsonrpsee", "substrate-compat"] }
```

And the result was the same:

![image](https://github.com/rust-random/getrandom/assets/142290531/b231e59d-c150-418c-9df0-39515dd47040)

Cheers,

**Comment by newpavlov** [comment]
What do you get for the snippet in my previous comment?

It looks like something is wrong with your build configuration. Enabling the `custom` feature should make the "target is not supported" compilation error impossible.

**Comment by newpavlov** [comment]
Duh. I've missed the crucial part: the error is for `getrandom v0.1`, not for v0.2. No wonders that setting features for v0.2 had no effect. The best solution would be to update (or patch) dependencies which pull v0.1 to work with v0.2.

**Comment by blue-freedom-technologies** [comment]
`What do you get for the snippet in my previous comment?`
![image](https://github.com/rust-random/getrandom/assets/142290531/9f0fa804-f6e4-4867-b7aa-026a757a9a34)


And after patching the libraries that are calling for "getrandom-0.1.16"
![image](https://github.com/rust-random/getrandom/assets/142290531/3d6b74db-42c1-4bdc-b9db-4ef7f5d82c4c)

The same error message:
![image](https://github.com/rust-random/getrandom/assets/142290531/7fa68b7a-4a0e-4a1e-9241-2365d5196f95)

We have created a public repo whit the test-app in [here](https://github.com/blue-freedom-technologies/test-app/tree/main).

If you want to have a look.

Cheers,

**Comment by newpavlov** [comment]
You still depend on `getrandom v0.1` as can be clearly seen in the path on your last screenshot. You should find which dependency in your project pulls `getrandom v0.1` and patch it to use v0.2. If `getrandom v0.1` is pulled through an older version of `rand`, then you should patch dependency which uses it.

**Comment by newpavlov** [comment]
Closing this issue since it is caused by `getrandom v0.1`.

**Comment by blue-freedom-technologies** [comment]
Not quite.

Because the cc compiler is failing and that's why this is reverting for the  getrandom v0.1

```
Running `/home/silveira/bluefreedom/test-app/target/debug/build/wasmtime-runtime-af8c978cc181d296/build-script-build`
The following warnings were emitted during compilation:

warning: cc: error: unrecognized argument in option ‘-mabi=ilp32’
warning: cc: note: valid arguments to ‘-mabi=’ are: ms sysv
warning: cc: error: unrecognized argument in option ‘-mcmodel=medany’
warning: cc: note: valid arguments to ‘-mcmodel=’ are: 32 kernel large medium small

error: failed to run custom build command for `wasmtime-runtime v8.0.1`

Caused by:
  process didn't exit successfully: `/home/silveira/bluefreedom/test-app/target/debug/build/wasmtime-runtime-af8c978cc181d296/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=src/helpers.c
  TARGET = Some("riscv32imac-esp-espidf")
  OPT_LEVEL = Some("z")
  HOST = Some("x86_64-unknown-linux-gnu")
  cargo:rerun-if-env-changed=CC_riscv32imac-esp-espidf
  CC_riscv32imac-esp-espidf = None
  cargo:rerun-if-env-changed=CC_riscv32imac_esp_espidf
  CC_riscv32imac_esp_espidf = None
  cargo:rerun-if-env-changed=TARGET_CC
  TARGET_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  RUSTC_LINKER = Some("ldproxy")
  cargo:rerun-if-env-changed=CROSS_COMPILE
  CROSS_COMPILE = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("a,c,m")
  cargo:rerun-if-env-changed=CFLAGS_riscv32imac-esp-espidf
  CFLAGS_riscv32imac-esp-espidf = None
  cargo:rerun-if-env-changed=CFLAGS_riscv32imac_esp_espidf
  CFLAGS_riscv32imac_esp_espidf = None
  cargo:rerun-if-env-changed=TARGET_CFLAGS
  TARGET_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  running: "cc" "-Os" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-march=rv32imac" "-mabi=ilp32" "-mcmodel=medany" "-Wall" "-Wextra" "-DCFG_TARGET_OS_espidf" "-DCFG_TARGET_ARCH_riscv32" "-o" "/home/silveira/bluefreedom/test-app/target/riscv32imac-esp-espidf/debug/build/wasmtime-runtime-d75f6ee2ec7ef9d7/out/src/helpers.o" "-c" "src/helpers.c"
  cargo:warning=cc: error: unrecognized argument in option ‘-mabi=ilp32’

  cargo:warning=cc: note: valid arguments to ‘-mabi=’ are: ms sysv

  cargo:warning=cc: error: unrecognized argument in option ‘-mcmodel=medany’

  cargo:warning=cc: note: valid arguments to ‘-mcmodel=’ are: 32 kernel large medium small

  exit status: 1

  --- stderr


  error occurred: Command "cc" "-Os" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-march=rv32imac" "-mabi=ilp32" "-mcmodel=medany" "-Wall" "-Wextra" "-DCFG_TARGET_OS_espidf" "-DCFG_TARGET_ARCH_riscv32" "-o" "/home/silveira/bluefreedom/test-app/target/riscv32imac-esp-espidf/debug/build/wasmtime-runtime-d75f6ee2ec7ef9d7/out/src/helpers.o" "-c" "src/helpers.c" with args "cc" did not execute successfully (status code exit status: 1).

warning: build failed, waiting for other jobs to finish...

 ```

Cheers,

**Comment by josephlr** [comment]
This issue tracker is probably not the best place to discuss unrelated build issues. Those should generally be brought up on the project specific issue trackers. If there are issues related to `getrandom 0.2`, feel free to open another issue.
