### ISSUE TITLE
Tracking issue for 0.2.0

### ISSUE THREAD

**Issue by josephlr** [rust-random/getrandom#98]
In the process of addressing #94, we realized that some of the changes we want to do would require breaking backwards compatibility. If we are going to release a version 0.2, we should consider other changes to `getrandom`.

A potential list is below. @dhardy and @newpavlov  feel free to edit this to include your own ideas.

- [x] Only expose the `std` traits if the `std` feature is enabled (see #94 and #96)
  - This is needed for https://github.com/rust-lang/rust/pull/62082
- [ ] Think about having default features
  - What should these be?
- [x] ~~Rename features to allow for grouping of dependencies~~
  - ~~`wasm-bindgen -> bindgen`, would make it much easier to use `js_sys` or `web_sys`.~~
  - Moot, now that #109 removed those features.
- [x] The default behavior for `wasm32-unknown-unknown` (with no explicit features). Options are:
  - Always fail (current implementation)
  - **Compile error** (current 0.2 behavior, see #84) 
  - Default to `bindgen`
- [x] Cleanup `wasm32` error codes
  - Implemented in #146 
- [x] Custom Randomness (#4) 
  - Can we make a solution that does not require unsafe code for users?
- [x] Feature for CPU randomness (#84)
  - If we add this, then it might make sense to remove explicit support for `hermit`, `l4re`, and `uefi` and just use this feature instead, as these platforms (especially UEFI) have multiple ways to get randomness.
- [x] Minimum Rust Version
  - #136 increases the MSRV to 1.33
  - Do we want to increase this further? Bumping to 1.34 would let us use [`TryInto`](https://doc.rust-lang.org/core/convert/trait.TryInto.html), which could be useful.
  - #159 Bumped to 1.34
- [x] Documentation
  - Implementation at #135 

If you have suggestions, please comment!

**Comment by newpavlov** [comment]
Unfortunately we probably still can't use compilation error by default for `wasm32-unknown-unknown`, since it would require bumping `rand`/`rand_core` versions.

I like the idea of replacing support for `hermit`, `l4re`, and `uefi` with `rdrand` flag, but I am bit unsure about implications for `rand`, since again strictly speaking it can be considered a breaking change. :/

>wasm-bindgen -> bindgen, would make it much easier to use js_sys or web_sys.

I am still not sure why would we want to use `web_sys` instead of `wasm-bindgen` directly.

**Comment by josephlr** [comment]
> Unfortunately we probably still can't use compilation error by default for `wasm32-unknown-unknown`, since it would require bumping `rand`/`rand_core` versions (i.e. breaking change leaks downstream in this case).

Hmm, that would be true. We could consider dividing the issues into "things that would require `rand 0.8`" and "things we could make work with `rand 0.7`".

> I like the idea of replacing support for `hermit`, `l4re`, and `uefi` with `rdrand` flag, but I am bit unsure about implications for `rand`, since again strictly speaking it can be considered a breaking change. :/

I mean we could always cop out and say those platforms weren't officially supported by `rand` yet and so it's not a breaking change (as all of these are new-ish targets, it might be fine).

> > wasm-bindgen -> bindgen, would make it much easier to use js_sys or web_sys.
> 
> I am still not sure why would we want to use `web_sys` instead of `wasm-bindgen` directly.

A fair point, I guess what I meant here is that _if_ we want to do something like this, we should rename the feature. I'll try to see if the code would be any better using `js_sys`. I think this would be easier to talk about with actual code.

**Comment by dhardy** [comment]
> (i.e. breaking change leaks downstream in this case)

We could use a feature-flag to re-enable (perhaps `dummy-wasm32-unknown`). But I don't recall any reason we shouldn't keep this behaviour as the default for `wasm32-unknown-unknown`; as @newpavlov has said a couple of times it's a not-quite-standardised target that can hopefully be dropped at some point.

> Custom Randomness (#4) 

IMO this is not an urgent issue (at least, I've seen very little demand for it). There is already a safe alternative: a Cargo patch to replace the crate.

> Feature for CPU randomness (#84) 

There are multiple aspects to this:

- Does it do anything on targets with good alternative sources?
- If so, does it replace that source or does it get used as a fallback (where failure is possible)?
- Do we, as suggested, drop support for targets like UEFI and SGX where CPU randomness is our only option anyway?

**Comment by josephlr** [comment]
I've created a [0.2 branch](https://github.com/rust-random/getrandom/tree/0.2) to track breaking changes to `getrandom`. PRs that make breaking changes should be submitted/merged against that branch.

**Comment by newpavlov** [comment]
Maybe we also should deprecate the `log` feature? IIRC it was mostly useful for WASM backends and I haven't seen anyone to enable this feature directly and it's not cascaded from the `rand` crates.

**Comment by CryZe** [comment]
Both cargo and the wasm target are still way too broken to remove the dummy implementation for rand / getrandom's wasm32-unknown-unknown support. I'd say remove the dummy implementation is likely possible once all the cargo bugs are fixed, but that's not going to happen anytime soon.

**Comment by josephlr** [comment]
> Both cargo and the wasm target are still way too broken to remove the dummy implementation for rand / getrandom's wasm32-unknown-unknown support.

@CryZe what do you mean? Our plan (see #109) is to give users of `rand/getrandom` a way to set a custom RNG source (similar to how [Custom Allocators](https://doc.rust-lang.org/std/alloc/trait.GlobalAlloc.html) work) on unsupported targets (which would include `wasm32-unknown-unknown`). Is there a reason that wouldn't work for your use-case?

Having the dummy impl makes debugging issues very hard, as the dummy impl fails at runtime as opposed to compile time.

**Comment by CryZe** [comment]
Ah, I think that would work then.

**Comment by josephlr** [comment]
@newpavlov I think dropping the `log` feature is also a good idea. We should focus on getting any relevant error info into the `Error` structure itself.

**Comment by newpavlov** [comment]
@josephlr 
Maybe it's worth to update the OP list?

**Comment by josephlr** [comment]
@newpavlov @dhardy I updated the list. I think we can release `0.2` after #136 and #135 are reviewed an merged.

**Comment by vks** [comment]
I think we should consider bumping MSRV to 1.36, see https://github.com/rust-random/rand/pull/987.

**Comment by newpavlov** [comment]
`getrandom` is not dependent on `alloc`, so there is no reason to bump MSRV to 1.36 (but I would prefer if `rand v0.8` and `rand-distr v0.3` had MSRV equal to 1.36). I don't think we have to keep MSRV synchronized across all `rand` crates.

**Comment by Lokathor** [comment]
Increasing from 1.33 to 1.34 is entirely reasonable, since that's current Debian Stable.
